#+TITLE: Nate's Emacs Config
#+STARTUP: indent

* Manifesto

- Prefer navive solutions to packages when possible
- Menus and prompts are better than muscle memory
- Consistency is more important than convinence
- =use-package= is /the way/.

* Look and feel

** Indentation

Recently, I made a switch from space indentation to tabs. If you're interested in my reasoning feel free to check out
[[https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/][this reddit thread]]. tl;dr: tabs are far superiour to spaces for some people with visual impairments, and that is reason
enough for me.

However, as in most things, the best option is somewhere in the middle of a polarized debate. Tabs are the more
accessible option for indentation, but suck for /alignment/. The solution is to just use both: tabs for indentation,
spaces for alignment. Fortunately, someone has [[https://github.com/jcsalomon/smarttabs][already taken care of this for us]].

Note that I have set the default of =indent-tabs-mode= to use spaces. I am in the process of converting my projects to
tabs, but the industry standard is spaces. I use =dir-locals= to enable tabs for my projects and wherever else I'm able.
